import { readFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { CompanyInfo } from '../types.js';

/**
 * Find the company root by walking up from a starting directory.
 * Looks for CLAUDE.md with "Generated by The Company" marker.
 */
export function findCompanyRoot(start?: string): string | null {
  let dir = resolve(start ?? process.cwd());

  for (let i = 0; i < 10; i++) {
    const cm = join(dir, 'CLAUDE.md');
    if (existsSync(cm)) {
      const content = readFileSync(cm, 'utf-8');
      if (content.includes('Generated by The Company')) {
        return dir;
      }
    }
    const parent = resolve(dir, '..');
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

/**
 * Extract company name from CLAUDE.md (first H1 heading).
 */
export function getCompanyName(companyRoot: string): string {
  const cm = join(companyRoot, 'CLAUDE.md');
  if (!existsSync(cm)) return 'Unknown Company';

  for (const line of readFileSync(cm, 'utf-8').split('\n')) {
    if (line.startsWith('# ')) {
      return line.slice(2).trim();
    }
  }
  return 'Unknown Company';
}

/**
 * Get company info.
 */
export function getCompanyInfo(companyRoot: string): CompanyInfo {
  return {
    name: getCompanyName(companyRoot),
    root: companyRoot,
  };
}

/**
 * Require company root or exit with error.
 */
export function requireCompany(): CompanyInfo {
  const root = findCompanyRoot();
  if (!root) {
    console.error('Error: The Company 프로젝트를 찾을 수 없습니다.');
    console.error('  tc init으로 회사를 설립하거나, 회사 디렉토리에서 실행하세요.');
    process.exit(1);
  }
  return getCompanyInfo(root);
}
